export const darkTheme = {
  background: '#2c2c2c',
  primaryColor: '#286BFF',
  primaryColorHover: '#1651DB',
  secondaryColor: '#6c757d',
  secondaryColorHover: '#6c757ddd',
  textPrimary: '#ffffff',
  textSecondary: '#b5b5b5',
  borderColor: '#444444',
  backgroundSidebar: '#333333',
  backgroundNavbar: '#333333',
  spacingXSmall: '0.35rem',
  spacingSmall: '0.5rem',
  spacingMedium: '1rem',
  spacingLarge: '1.5rem',
  spacingXLarge: '2rem',
  fontSizeLg: '1.5rem',
  fontSizeBase: '1rem',
  borderRadius: '4px',
  sidebarWidth: '200px',
  sidebarText: '#E1E8ED',
  accentColor: '#FFAB4A'
};
